// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuitionPaymentAPI.Data;

#nullable disable

namespace TuitionPaymentAPI.Migrations
{
    [DbContext(typeof(TuitionDbContext))]
    partial class TuitionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TuitionPaymentAPI.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TuitionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PaymentId");

                    b.HasIndex("TuitionId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TuitionPaymentAPI.Models.RateLimit", b =>
                {
                    b.Property<int>("RateLimitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CallCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastCall")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("RateLimitId");

                    b.HasIndex("StudentNo", "Endpoint", "Date");

                    b.ToTable("RateLimits");
                });

            modelBuilder.Entity("TuitionPaymentAPI.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.HasIndex("StudentNo")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CreatedAt = new DateTime(2025, 11, 20, 17, 3, 57, 94, DateTimeKind.Utc).AddTicks(2690),
                            Email = "ahmet.yilmaz@university.edu",
                            Name = "Ahmet Yılmaz",
                            StudentNo = "20210001"
                        },
                        new
                        {
                            StudentId = 2,
                            CreatedAt = new DateTime(2025, 11, 20, 17, 3, 57, 94, DateTimeKind.Utc).AddTicks(2780),
                            Email = "ayse.demir@university.edu",
                            Name = "Ayşe Demir",
                            StudentNo = "20210002"
                        },
                        new
                        {
                            StudentId = 3,
                            CreatedAt = new DateTime(2025, 11, 20, 17, 3, 57, 94, DateTimeKind.Utc).AddTicks(2780),
                            Email = "mehmet.kaya@university.edu",
                            Name = "Mehmet Kaya",
                            StudentNo = "20210003"
                        },
                        new
                        {
                            StudentId = 4,
                            CreatedAt = new DateTime(2025, 11, 20, 17, 3, 57, 94, DateTimeKind.Utc).AddTicks(2780),
                            Email = "fatma.oz@university.edu",
                            Name = "Fatma Öz",
                            StudentNo = "20210004"
                        },
                        new
                        {
                            StudentId = 5,
                            CreatedAt = new DateTime(2025, 11, 20, 17, 3, 57, 94, DateTimeKind.Utc).AddTicks(2780),
                            Email = "ali.sahin@university.edu",
                            Name = "Ali Şahin",
                            StudentNo = "20210005"
                        });
                });

            modelBuilder.Entity("TuitionPaymentAPI.Models.Tuition", b =>
                {
                    b.Property<int>("TuitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TuitionId");

                    b.HasIndex("StudentId", "Term");

                    b.ToTable("Tuitions");

                    b.HasData(
                        new
                        {
                            TuitionId = 1,
                            Balance = 50000m,
                            CreatedAt = new DateTime(2025, 11, 20, 17, 3, 57, 94, DateTimeKind.Utc).AddTicks(5840),
                            PaidAmount = 0m,
                            Status = "UNPAID",
                            StudentId = 1,
                            Term = "2024-Fall",
                            TotalAmount = 50000m,
                            UpdatedAt = new DateTime(2025, 11, 20, 17, 3, 57, 94, DateTimeKind.Utc).AddTicks(5910)
                        },
                        new
                        {
                            TuitionId = 2,
                            Balance = 25000m,
                            CreatedAt = new DateTime(2025, 11, 20, 17, 3, 57, 94, DateTimeKind.Utc).AddTicks(5990),
                            PaidAmount = 25000m,
                            Status = "PARTIAL",
                            StudentId = 2,
                            Term = "2024-Fall",
                            TotalAmount = 50000m,
                            UpdatedAt = new DateTime(2025, 11, 20, 17, 3, 57, 94, DateTimeKind.Utc).AddTicks(5990)
                        },
                        new
                        {
                            TuitionId = 3,
                            Balance = 0m,
                            CreatedAt = new DateTime(2025, 11, 20, 17, 3, 57, 94, DateTimeKind.Utc).AddTicks(5990),
                            PaidAmount = 50000m,
                            Status = "PAID",
                            StudentId = 3,
                            Term = "2024-Fall",
                            TotalAmount = 50000m,
                            UpdatedAt = new DateTime(2025, 11, 20, 17, 3, 57, 94, DateTimeKind.Utc).AddTicks(5990)
                        },
                        new
                        {
                            TuitionId = 4,
                            Balance = 50000m,
                            CreatedAt = new DateTime(2025, 11, 20, 17, 3, 57, 94, DateTimeKind.Utc).AddTicks(5990),
                            PaidAmount = 0m,
                            Status = "UNPAID",
                            StudentId = 4,
                            Term = "2024-Fall",
                            TotalAmount = 50000m,
                            UpdatedAt = new DateTime(2025, 11, 20, 17, 3, 57, 94, DateTimeKind.Utc).AddTicks(5990)
                        });
                });

            modelBuilder.Entity("TuitionPaymentAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 11, 20, 17, 3, 57, 269, DateTimeKind.Utc).AddTicks(5700),
                            PasswordHash = "$2a$11$Y1qZCLkc6XPN3kKbXaAu4ueM9EadGNjCr9jflQzVkCHID/jAGrTTK",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 11, 20, 17, 3, 57, 371, DateTimeKind.Utc).AddTicks(5230),
                            PasswordHash = "$2a$11$TsvldFLTlImNfuwTNctioubOVaRsEhuywtHm6OHmNg8dGenHnkXhK",
                            Role = "BankingSystem",
                            Username = "bankapi"
                        });
                });

            modelBuilder.Entity("TuitionPaymentAPI.Models.Payment", b =>
                {
                    b.HasOne("TuitionPaymentAPI.Models.Tuition", "Tuition")
                        .WithMany("Payments")
                        .HasForeignKey("TuitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tuition");
                });

            modelBuilder.Entity("TuitionPaymentAPI.Models.Tuition", b =>
                {
                    b.HasOne("TuitionPaymentAPI.Models.Student", "Student")
                        .WithMany("Tuitions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TuitionPaymentAPI.Models.Student", b =>
                {
                    b.Navigation("Tuitions");
                });

            modelBuilder.Entity("TuitionPaymentAPI.Models.Tuition", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
