// <auto-generated />
using System;
using APIGateway.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIGateway.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20251121173140_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("APIGateway.Models.RateLimit", b =>
                {
                    b.Property<int>("RateLimitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CallCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastCall")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("RateLimitId");

                    b.HasIndex("StudentNo", "Endpoint", "Date")
                        .HasDatabaseName("IX_RateLimit_StudentNo_Endpoint_Date");

                    b.ToTable("RateLimits", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
